<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Free',
                'slug' => 'free',
                'description' => 'Perfect for testing and small projects',
                'price' => 0,
                'billing_cycle' => 'lifetime',
                'media_limit' => 2500,
                'max_sites' => 1,
                'features' => [
                    'Up to 2,500 media files',
                    'AWS S3 integration',
                    'Basic support',
                    '1 site activation',
                ],
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Bronze',
                'slug' => 'bronze',
                'description' => 'Great for small websites and blogs',
                'price' => 39.00,
                'billing_cycle' => 'yearly',
                'media_limit' => 2000,
                'max_sites' => 1,
                'features' => [
                    'Up to 2,000 media files',
                    'AWS S3 integration',
                    'CloudFront CDN',
                    'Priority email support',
                    '1 site activation',
                    '1 year of updates',
                ],
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Silver',
                'slug' => 'silver',
                'description' => 'Ideal for growing websites',
                'price' => 59.00,
                'billing_cycle' => 'yearly',
                'media_limit' => 6000,
                'max_sites' => 1,
                'features' => [
                    'Up to 6,000 media files',
                    'AWS S3 integration',
                    'CloudFront CDN',
                    'Priority email support',
                    '1 site activation',
                    '1 year of updates',
                ],
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Gold',
                'slug' => 'gold',
                'description' => 'Perfect for medium-sized businesses',
                'price' => 149.00,
                'billing_cycle' => 'yearly',
                'media_limit' => 20000,
                'max_sites' => 3,
                'features' => [
                    'Up to 20,000 media files',
                    'AWS S3 integration',
                    'CloudFront CDN',
                    'Priority email support',
                    '3 site activations',
                    '1 year of updates',
                    'Advanced analytics',
                ],
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Platinum',
                'slug' => 'platinum',
                'description' => 'For large websites and agencies',
                'price' => 199.00,
                'billing_cycle' => 'yearly',
                'media_limit' => 40000,
                'max_sites' => 5,
                'features' => [
                    'Up to 40,000 media files',
                    'AWS S3 integration',
                    'CloudFront CDN',
                    'Priority email support',
                    '5 site activations',
                    '1 year of updates',
                    'Advanced analytics',
                    'White-label options',
                ],
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Gem',
                'slug' => 'gem',
                'description' => 'Perfect for large affiliate sites',
                'price' => 349.00,
                'billing_cycle' => 'yearly',
                'media_limit' => 100000,
                'max_sites' => 5,
                'features' => [
                    'Up to 100,000 media files',
                    'AWS S3 integration',
                    'CloudFront CDN',
                    'Priority email support',
                    '5 site activations',
                    '1 year of updates',
                    'Advanced analytics',
                    'WooCommerce integration',
                    'EDD integration',
                    'WPML support',
                    'Assets Pull',
                    'Multisite supported',
                ],
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => '500K',
                'slug' => '500k',
                'description' => 'For massive affiliate networks',
                'price' => 799.00,
                'billing_cycle' => 'yearly',
                'media_limit' => 500000,
                'max_sites' => 10,
                'features' => [
                    'Up to 500,000 media files',
                    'AWS S3 integration',
                    'CloudFront CDN',
                    'Priority email support',
                    '10 site activations (unlimited sites)',
                    '1 year of updates',
                    'Advanced analytics',
                    'WooCommerce integration',
                    'EDD integration',
                    'WPML support',
                    'Assets Pull',
                    'Multisite supported',
                    'Dedicated account manager',
                ],
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Unlimited',
                'slug' => 'unlimited',
                'description' => 'For enterprise and high-volume sites',
                'price' => 1199.00,
                'billing_cycle' => 'yearly',
                'media_limit' => null, // Unlimited
                'max_sites' => 20,
                'features' => [
                    'Unlimited media files',
                    'AWS S3 integration',
                    'CloudFront CDN',
                    'Priority email support',
                    '20 site activations (unlimited sites)',
                    '1 year of updates',
                    'Advanced analytics',
                    'White-label options',
                    'Dedicated support',
                    'Custom integrations',
                    'WooCommerce integration',
                    'EDD integration',
                    'WPML support',
                    'Assets Pull',
                    'Multisite supported',
                ],
                'is_active' => true,
                'sort_order' => 8,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::create($plan);
        }
    }
}
